config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'answers#index'

  resources :answers, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ActiveHash::Base
  self.data = [
    {id: 1, name: 'チベットスナギツネ'},
    {id: 2, name: 'キャンディ'},
    {id: 3, name: 'クルーザー'},
    {id: 4, name: 'コイン'},
    {id: 5, name: 'ルビーの指輪'},
    {id: 6, name: 'あんぱん'},
    {id: 7, name: '自転車'},
    {id: 8, name: 'ブランドバッグ'},
    {id: 9, name: '紙袋'},
    {id: 10, name: 'カードキー'},
    {id: 11, name: 'ロープ'},
    {id: 12, name: '麦わら帽子'},
    {id: 13, name: 'コーヒー'},
    {id: 14, name: '座布団'},
    {id: 15, name: '口紅'},
    {id: 16, name: '札束'},
    {id: 17, name: '花火'},
    {id: 18, name: '仏像'},
    {id: 19, name: 'バール'},
    {id: 20, name: 'おもちゃのピアノ'},
    {id: 21, name: '芝刈り機'},
    {id: 22, name: 'ライダースジャケット'},
    {id: 23, name: '折り畳み傘'},
    {id: 24, name: '物干し竿'},
    {id: 25, name: 'コーラ'},
    {id: 26, name: 'フライパン'},
    {id: 27, name: 'Tシャツ'},
    {id: 28, name: 'スマホ'},
    {id: 29, name: 'バケツ'},
    {id: 30, name: 'カブトムシ'}
  ]
end

app/models/theme.rb
class Theme < ActiveHash::Base
  self.data = [
    {id: 1, body: 'おしゃれな河童たちの最先端トレンドはこれだ'},
    {id: 2, body: '急募！関西人と大阪人を見分ける方法'},
    {id: 3, body: 'ハリウッド忍者の特徴を教えてください'},
    {id: 4, body: '成績優秀、スポーツ万能、なんでもできるタカシ君がアルバイトの面接に落ちました。なぜ？'},
    {id: 5, body: 'このラーメン屋には二度と行きたくない！その理由とは'},
    {id: 6, body: '帰ってきたウルトラマンは、何故帰ってきたのでしょう？'},
    {id: 7, body: 'メルヘン検定１級の試験内容とは？'},
    {id: 8, body: '世界で一番優しい嘘とはどんな嘘？'},
    {id: 9, body: '絶対GACKTが言わなそうなセリフを言ってください'},
    {id: 10, body: '女子力ってどんな力？'},
    {id: 11, body: '乗客がタクシー運転手に激怒、なぜ？'},
    {id: 12, body: '迷惑メールと知りつつも思わず開封してしまったタイトル(件名)とは？'},
    {id: 13, body: '藤岡弘が一度やってみたかった贅沢とは？'},
    {id: 14, body: '新型冷蔵庫の新機能とは？'},
    {id: 15, body: '「間違いなく、その場しのぎ」と思われる言葉をいってください。'},
    {id: 16, body: 'マニアックすぎて売れない写真集のタイトル'},
    {id: 17, body: '「何で空は青いの？」子供の質問に答えてください。'},
    {id: 18, body: '１０年後の自分から手紙が届いた。何て書いてあった？'},
    {id: 19, body: '富士山頂にて謎のボタンを発見。押すとどうなる？'},
    {id: 20, body: '夜空を眺めながら彼氏に語られたら嫌な話とは？'},
    {id: 21, body: '酢豚の中にパイナップルが入っている理由とは？'},
    {id: 22, body: 'どんな人でも当選させるという凄腕選挙参謀。その驚くべき戦略とは？'},
    {id: 23, body: 'こんな避難訓練は嫌だ！'},
    {id: 24, body: '普通のレスラーと覆面レスラーの違いをなんでもいいので一つ挙げなさい。'},
    {id: 25, body: 'サッカーに新しい反則が追加されました。どんな反則？'},
    {id: 26, body: '履歴書に決して書いてはいけない趣味とは？'},
    {id: 27, body: '「この人、カレー好きなんだろな。」なぜそう思った？'},
    {id: 28, body: 'マザコン男の見分け方を教えて下さい。'},
    {id: 29, body: '絶対５００万枚売れるアルバムタイトルを書いて下さい'},
    {id: 30, body: '「ジョジョの奇妙な冒険」でお馴染みのセリフ「無駄無駄無駄無駄無駄無駄ァーッ！！」さて、何が無駄？'}
  ]
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def index
  end

  def new
    # theme_num = Random.rand(1 .. 30)
    num = [*1..30].sample
    @theme = Theme.find_by_id num
    nums = [*1..30].sample(3)
    @item_1 = Item.find_by_id nums[0]
    @item_2 = Item.find_by_id nums[1]
    @item_3 = Item.find_by_id nums[2]
    # binding.pry
  end

  def create
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/_header.html.haml
%header.header_logo
  = link_to root_path, class: 'header_logo__link', data:{turbolinks: :false} do
    = image_tag "4953.png", class: 'header_logo__link__image', size: '64x48'
    %span Fox and Candy !
    = image_tag "0080.png", class: 'header_logo__link__image', size: '75x48'

app/views/answers/index.html.haml
= render "header"

%main.answer_index
  %h4.answer_index__description
    %br'Fox and Candy !'は、かの有名パーティゲームをリスペクトした
    %br 大喜利チャレンジアプリです。
    %br 出題されたお題はSNS（Twitter）にシェアできます。
  
  %h4.answer_index__rules
    %br【ルール説明】
    %br １：下のボタンをクリックするとお題と使用可能なアイテムが３つ表示されます。
    %br ２：シェアボタンを押すと、お題とアイテムをSNSにシェアできます。
    %br ３：アイテムを１個以上使って、ナイスな回答をSNSへ呟いてみましょう！
  
  = link_to 'チャレンジする', new_answer_path, class: 'answer_index__link', data:{turbolinks: :false}

app/views/answers/new.html.haml
= render "header"

%main.answer_new
  = form_with url: root_path, local: true, class: 'answer_new__form' do |f|

    .answer_new__form__item
      %label.bold{ for: "theme" } 【お題】
      %br
      %label 
        = @theme.body
    
    .answer_new__form__item
      %label.bold{ for: "item" } 【使用可能アイテム】
      %br
      %label 
        = @item_1.name + ' / ' + @item_2.name + ' / ' + @item_3.name

    .answer_new__form__item
      %label{ for: "item" } ※最低1個はアイテムを使用して回答してみてね！

    .answer_new__form__item
      .answer_new__form__item--wrap
        %a.twitter-share-button{data:{hashtags: "Fox and Candy !"}, data:{url: "http://54.65.143.255/"}, data:{lang: "ja"}, data:{'show-count' => "false"}, data:{size: "large"}, data:{text: "#Fox_and_Candy\n#お題\n##{@theme.body}\n#使用可能アイテム\n##{@item_1.name + '_' + @item_2.name + '_' + @item_3.name}\n#最低1個はアイテムを使用して回答してみてね\n#http://54.65.143.255/"}, href: "https://twitter.com/share?ref_src=twsrc%5Etfw"} ツイート
        %script{async: "", charset: "utf-8", src: "https://platform.twitter.com/widgets.js"}
        %span.twitter-span ←Twitterでシェアして回答しよう！
  
  =link_to 'トップページに戻る', root_path, class: 'answer_new__link', data:{turbolinks: :false}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FoxAndCandy
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield